"""Generate Wave 33: deterministic coordinated pipeline exercises."""

from gen_wave32 import exercise, emit_refs, emit_rust


CASES = [
    # 1. Offsets and progress
    ("offset-siguiente", "offsets · siguiente", "Calcular el próximo offset esperado.", "procesado = 7\nresultado = procesado + 1\nprint(resultado)", 8, "offsets"),
    ("offset-contiguo", "offsets · continuidad", "Aceptar solo el offset contiguo.", "ultimo, recibido = 4, 5\nresultado = recibido == ultimo + 1\nprint(resultado)", True, "offsets"),
    ("offset-huecos", "offsets · huecos", "Detectar offsets ausentes en un rango.", "recibidos = {3, 4, 6, 8}\nresultado = [n for n in range(3, 9) if n not in recibidos]\nprint(resultado)", [5, 7], "offsets"),
    ("offset-por-particion", "offsets · por partición", "Mantener progreso independiente por partición.", "eventos = [(0, 3), (1, 2), (0, 4)]\nprogreso = {}\nfor particion, offset in eventos: progreso[particion] = max(offset, progreso.get(particion, -1))\nresultado = progreso\nprint(resultado)", {0: 4, 1: 2}, "offsets"),
    ("offset-lag", "offsets · lag", "Calcular atraso respecto del último disponible.", "disponible = {0: 9, 1: 7}\nprocesado = {0: 6, 1: 7}\nresultado = {p: disponible[p] - procesado[p] for p in sorted(disponible)}\nprint(resultado)", {0: 3, 1: 0}, "offsets"),
    ("offset-suite", "offsets · suite", "Avanzar progreso contiguo y reportar huecos y lag.", "recibidos = {0: [3, 4, 6], 1: [1, 2, 3]}\nultimo = {0: 2, 1: 0}; disponible = {0: 6, 1: 3}\nfor p in sorted(recibidos):\n    while ultimo[p] + 1 in recibidos[p]: ultimo[p] += 1\nresultado = {'progreso': ultimo, 'lag': {p: disponible[p] - ultimo[p] for p in sorted(ultimo)}}\nprint(resultado)", {"progreso": {0: 4, 1: 3}, "lag": {0: 2, 1: 0}}, "offsets"),

    # 2. Acknowledgements
    ("ack-marcar", "ack · marcar", "Marcar un mensaje como confirmado.", "confirmados = {'m1'}\nconfirmados.add('m2')\nresultado = sorted(confirmados)\nprint(resultado)", ["m1", "m2"], "acks"),
    ("ack-pendientes", "ack · pendientes", "Listar mensajes todavía no confirmados.", "enviados = ['m1', 'm2', 'm3']\nconfirmados = {'m1', 'm3'}\nresultado = [m for m in enviados if m not in confirmados]\nprint(resultado)", ["m2"], "acks"),
    ("ack-cumulativo", "ack · acumulativo", "Confirmar todos los offsets hasta un límite.", "offsets = [3, 4, 5, 6]\nack = 5\nresultado = [n for n in offsets if n <= ack]\nprint(resultado)", [3, 4, 5], "acks"),
    ("ack-desorden", "ack · desorden", "Conservar confirmaciones fuera de orden hasta cerrar huecos.", "acks = {4, 6, 5}\nbase = 3\nwhile base + 1 in acks: base += 1\nresultado = base\nprint(resultado)", 6, "acks"),
    ("ack-reintentar", "ack · reintentar", "Seleccionar mensajes no confirmados para reenvío.", "enviados = [('m1', 1), ('m2', 2), ('m3', 3)]\nconfirmados = {'m1'}\nresultado = [m for m in enviados if m[0] not in confirmados]\nprint(resultado)", [("m2", 2), ("m3", 3)], "acks"),
    ("ack-suite", "ack · suite", "Combinar ack individual y acumulativo en un resumen.", "mensajes = [('m1', 3), ('m2', 4), ('m3', 5), ('m4', 6)]\nindividuales = {'m4'}; acumulativo = 4\nconfirmados = [mid for mid, off in mensajes if off <= acumulativo or mid in individuales]\nresultado = {'confirmados': confirmados, 'pendientes': [mid for mid, _ in mensajes if mid not in confirmados]}\nprint(resultado)", {"confirmados": ["m1", "m2", "m4"], "pendientes": ["m3"]}, "acks"),

    # 3. Delivery deduplication
    ("entrega-primera", "entrega · primera", "Aceptar la primera aparición de cada id.", "ids = ['a', 'b', 'a', 'c']\nvistos, resultado = set(), []\nfor identificador in ids:\n    if identificador not in vistos: vistos.add(identificador); resultado.append(identificador)\nprint(resultado)", ["a", "b", "c"], "delivery"),
    ("entrega-duplicados", "entrega · duplicados", "Contar entregas duplicadas.", "ids = ['a', 'a', 'b', 'c', 'b']\nresultado = len(ids) - len(set(ids))\nprint(resultado)", 2, "delivery"),
    ("entrega-idempotente", "entrega · idempotencia", "Aplicar cada operación una sola vez.", "operaciones = [('x', 3), ('y', 2), ('x', 3)]\nvistos, total = set(), 0\nfor identificador, valor in operaciones:\n    if identificador not in vistos: vistos.add(identificador); total += valor\nresultado = total\nprint(resultado)", 5, "delivery"),
    ("entrega-por-clave", "entrega · por clave", "Deduplicar independientemente por consumidor.", "eventos = [('a', 'm1'), ('b', 'm1'), ('a', 'm1'), ('a', 'm2')]\nvistos, aceptados = set(), []\nfor consumidor, mensaje in eventos:\n    clave = (consumidor, mensaje)\n    if clave not in vistos: vistos.add(clave); aceptados.append(clave)\nresultado = aceptados\nprint(resultado)", [("a", "m1"), ("b", "m1"), ("a", "m2")], "delivery"),
    ("entrega-estado", "entrega · estado", "Conservar ids vistos junto al agregado.", "eventos = [('e1', 2), ('e2', 5), ('e1', 2)]\nestado = {'vistos': set(), 'total': 0}\nfor identificador, valor in eventos:\n    if identificador not in estado['vistos']: estado['vistos'].add(identificador); estado['total'] += valor\nresultado = {'vistos': sorted(estado['vistos']), 'total': estado['total']}\nprint(resultado)", {"vistos": ["e1", "e2"], "total": 7}, "delivery"),
    ("entrega-suite", "entrega · suite", "Deduplicar, agregar y emitir métricas de entrega.", "eventos = [('e1', 'a', 2), ('e2', 'a', 3), ('e1', 'a', 2), ('e3', 'b', 4)]\nvistos, total, duplicados = set(), {}, 0\nfor identificador, clave, valor in eventos:\n    if identificador in vistos: duplicados += 1; continue\n    vistos.add(identificador); total[clave] = total.get(clave, 0) + valor\nresultado = {'total': total, 'aceptados': len(vistos), 'duplicados': duplicados}\nprint(resultado)", {"total": {"a": 5, "b": 4}, "aceptados": 3, "duplicados": 1}, "delivery"),

    # 4. Checkpoints
    ("checkpoint-capturar", "checkpoints · capturar", "Capturar una copia inmutable del estado.", "estado = {'offset': 4, 'total': 9}\nresultado = dict(estado)\nprint(resultado)", {"offset": 4, "total": 9}, "checkpoints"),
    ("checkpoint-restaurar", "checkpoints · restaurar", "Restaurar estado desde un snapshot.", "snapshot = {'offset': 7, 'conteos': {'a': 2}}\nrestaurado = {'offset': snapshot['offset'], 'conteos': dict(snapshot['conteos'])}\nresultado = restaurado\nprint(resultado)", {"offset": 7, "conteos": {"a": 2}}, "checkpoints"),
    ("checkpoint-ultimo", "checkpoints · último", "Elegir el snapshot con mayor versión.", "snapshots = [(1, {'x': 2}), (3, {'x': 5}), (2, {'x': 4})]\nresultado = max(snapshots, key=lambda item: item[0])\nprint(resultado)", (3, {"x": 5}), "checkpoints"),
    ("checkpoint-validar", "checkpoints · validar", "Validar versión y campos requeridos.", "snapshot = {'version': 2, 'offset': 8, 'estado': {}}\nresultado = snapshot.get('version') == 2 and {'offset', 'estado'} <= snapshot.keys()\nprint(resultado)", True, "checkpoints"),
    ("checkpoint-delta", "checkpoints · delta", "Calcular cambios respecto del snapshot anterior.", "anterior = {'a': 2, 'b': 1}\nactual = {'a': 5, 'b': 1, 'c': 3}\nresultado = {k: actual[k] - anterior.get(k, 0) for k in sorted(actual) if actual[k] != anterior.get(k, 0)}\nprint(resultado)", {"a": 3, "c": 3}, "checkpoints"),
    ("checkpoint-suite", "checkpoints · suite", "Restaurar, aplicar eventos y crear un snapshot nuevo.", "snapshot = {'version': 1, 'offset': 2, 'total': 5}\neventos = [(3, 4), (4, 2)]\nestado = dict(snapshot)\nfor offset, valor in eventos:\n    if offset > estado['offset']: estado['offset'] = offset; estado['total'] += valor\nresultado = {'version': estado['version'] + 1, 'offset': estado['offset'], 'total': estado['total']}\nprint(resultado)", {"version": 2, "offset": 4, "total": 11}, "checkpoints"),

    # 5. Barriers
    ("barrera-llegadas", "barreras · llegadas", "Registrar particiones que alcanzaron una barrera.", "llegadas = [2, 0, 1]\nresultado = sorted(set(llegadas))\nprint(resultado)", [0, 1, 2], "barriers"),
    ("barrera-faltantes", "barreras · faltantes", "Detectar particiones pendientes.", "esperadas = {0, 1, 2, 3}\nllegadas = {0, 2}\nresultado = sorted(esperadas - llegadas)\nprint(resultado)", [1, 3], "barriers"),
    ("barrera-completa", "barreras · completa", "Decidir si la barrera está completa.", "esperadas = {0, 1, 2}\nllegadas = {2, 0, 1}\nresultado = llegadas == esperadas\nprint(resultado)", True, "barriers"),
    ("barrera-alinear", "barreras · alinear", "Calcular el offset seguro común.", "offsets = {0: 8, 1: 6, 2: 7}\nresultado = min(offsets.values())\nprint(resultado)", 6, "barriers"),
    ("barrera-buffer", "barreras · buffer", "Separar eventos posteriores a la barrera.", "eventos = [(4, 'a'), (7, 'b'), (6, 'c')]\nbarrera = 6\nresultado = ([e for e in eventos if e[0] <= barrera], [e for e in eventos if e[0] > barrera])\nprint(resultado)", ([(4, "a"), (6, "c")], [(7, "b")]), "barriers"),
    ("barrera-suite", "barreras · suite", "Alinear particiones y liberar buffers al completar.", "marcas = [(0, 5), (2, 7), (1, 6)]\nesperadas = {0, 1, 2}; offsets = {p: off for p, off in marcas}\nseguro = min(offsets.values()) if set(offsets) == esperadas else None\nbuffer = [(8, 'x'), (5, 'y'), (6, 'z')]\nresultado = {'completa': seguro is not None, 'seguro': seguro, 'liberados': [e for e in buffer if e[0] <= seguro]}\nprint(resultado)", {"completa": True, "seguro": 5, "liberados": [(5, "y")]}, "barriers"),

    # 6. Backpressure by credits
    ("credito-permitir", "backpressure · permitir", "Permitir emisión si quedan créditos.", "creditos = 2\nresultado = creditos > 0\nprint(resultado)", True, "backpressure"),
    ("credito-consumir", "backpressure · consumir", "Consumir un crédito por mensaje.", "creditos = 3\ncreditos -= 1\nresultado = creditos\nprint(resultado)", 2, "backpressure"),
    ("credito-reponer", "backpressure · reponer", "Reponer créditos hasta una capacidad.", "creditos, capacidad, ack = 1, 4, 3\nresultado = min(capacidad, creditos + ack)\nprint(resultado)", 4, "backpressure"),
    ("credito-por-worker", "backpressure · por worker", "Mantener créditos independientes.", "creditos = {'a': 2, 'b': 1}\nfor worker in ['a', 'b', 'a']: creditos[worker] -= 1\nresultado = creditos\nprint(resultado)", {"a": 0, "b": 0}, "backpressure"),
    ("credito-pausar", "backpressure · pausa", "Pausar cuando todos los consumidores están saturados.", "creditos = {'a': 0, 'b': 0}\nresultado = 'pausado' if not any(creditos.values()) else 'activo'\nprint(resultado)", "pausado", "backpressure"),
    ("credito-suite", "backpressure · suite", "Emitir con créditos, registrar pausas y reponer con acks.", "creditos, capacidad = 2, 3\neventos = [('emitir', None), ('emitir', None), ('emitir', None), ('ack', 2), ('emitir', None)]\nhistorial = []\nfor accion, valor in eventos:\n    if accion == 'ack': creditos = min(capacidad, creditos + valor); historial.append(('ack', creditos))\n    elif creditos > 0: creditos -= 1; historial.append(('emitido', creditos))\n    else: historial.append(('pausado', creditos))\nresultado = historial\nprint(resultado)", [("emitido", 1), ("emitido", 0), ("pausado", 0), ("ack", 2), ("emitido", 1)], "backpressure"),

    # 7. Lineage
    ("linaje-padre", "lineage · padre", "Consultar el padre directo de un artefacto.", "padres = {'b': 'a', 'c': 'b'}\nresultado = padres['c']\nprint(resultado)", "b", "lineage"),
    ("linaje-ancestros", "lineage · ancestros", "Recorrer ancestros hasta la raíz.", "padres = {'b': 'a', 'c': 'b', 'd': 'c'}\nactual, resultado = 'd', []\nwhile actual in padres: actual = padres[actual]; resultado.append(actual)\nprint(resultado)", ["c", "b", "a"], "lineage"),
    ("linaje-raices", "lineage · raíces", "Encontrar fuentes sin padres.", "nodos = {'a', 'b', 'c', 'd'}\npadres = {'b': 'a', 'c': 'a', 'd': 'b'}\nresultado = sorted(nodos - set(padres))\nprint(resultado)", ["a"], "lineage"),
    ("linaje-hijos", "lineage · hijos", "Construir hijos por nodo.", "padres = {'b': 'a', 'c': 'a', 'd': 'b'}\nhijos = {}\nfor hijo, padre in padres.items(): hijos.setdefault(padre, []).append(hijo)\nresultado = {k: sorted(v) for k, v in sorted(hijos.items())}\nprint(resultado)", {"a": ["b", "c"], "b": ["d"]}, "lineage"),
    ("linaje-impacto", "lineage · impacto", "Calcular descendientes afectados por una fuente.", "padres = {'b': 'a', 'c': 'a', 'd': 'b'}\nafectados = {'a'}\ncambio = True\nwhile cambio:\n    antes = len(afectados); afectados |= {h for h, p in padres.items() if p in afectados}; cambio = len(afectados) > antes\nresultado = sorted(afectados - {'a'})\nprint(resultado)", ["b", "c", "d"], "lineage"),
    ("linaje-suite", "lineage · suite", "Producir camino, raíces e impacto reproducibles.", "padres = {'limpio': 'crudo', 'agregado': 'limpio', 'reporte': 'agregado'}\nactual, camino = 'reporte', ['reporte']\nwhile actual in padres: actual = padres[actual]; camino.append(actual)\nfuente = camino[-1]\nresultado = {'camino': camino, 'fuente': fuente, 'profundidad': len(camino) - 1}\nprint(resultado)", {"camino": ["reporte", "agregado", "limpio", "crudo"], "fuente": "crudo", "profundidad": 3}, "lineage"),

    # 8. Replay
    ("replay-desde", "replay · desde offset", "Seleccionar eventos posteriores a un offset.", "eventos = [(1, 'a'), (2, 'b'), (3, 'c')]\ndesde = 1\nresultado = [e for e in eventos if e[0] > desde]\nprint(resultado)", [(2, "b"), (3, "c")], "replay"),
    ("replay-hasta", "replay · rango", "Reproducir un rango cerrado de offsets.", "eventos = [(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]\nresultado = [e for e in eventos if 2 <= e[0] <= 3]\nprint(resultado)", [(2, "b"), (3, "c")], "replay"),
    ("replay-deduplicar", "replay · deduplicar", "Evitar reaplicar ids ya incluidos en snapshot.", "eventos = [('e1', 2), ('e2', 3), ('e3', 4)]\nvistos = {'e1', 'e2'}\nresultado = [e for e in eventos if e[0] not in vistos]\nprint(resultado)", [("e3", 4)], "replay"),
    ("replay-reconstruir", "replay · reconstruir", "Reconstruir un agregado desde el log.", "eventos = [('a', 2), ('b', 3), ('a', 4)]\ntotal = {}\nfor clave, valor in eventos: total[clave] = total.get(clave, 0) + valor\nresultado = total\nprint(resultado)", {"a": 6, "b": 3}, "replay"),
    ("replay-comparar", "replay · comparar", "Comparar estado reconstruido con snapshot.", "snapshot = {'a': 6, 'b': 3}\nreconstruido = {'b': 3, 'a': 6}\nresultado = snapshot == reconstruido\nprint(resultado)", True, "replay"),
    ("replay-suite", "replay · suite", "Restaurar snapshot y reproducir solo eventos nuevos.", "snapshot = {'offset': 2, 'total': {'a': 5}, 'vistos': {'e1', 'e2'}}\neventos = [(2, 'e2', 'a', 3), (3, 'e3', 'a', 4), (4, 'e4', 'b', 2)]\ntotal = dict(snapshot['total']); vistos = set(snapshot['vistos']); offset = snapshot['offset']\nfor off, identificador, clave, valor in eventos:\n    if off > offset and identificador not in vistos: vistos.add(identificador); total[clave] = total.get(clave, 0) + valor; offset = off\nresultado = {'offset': offset, 'total': total, 'vistos': sorted(vistos)}\nprint(resultado)", {"offset": 4, "total": {"a": 9, "b": 2}, "vistos": ["e1", "e2", "e3", "e4"]}, "replay"),

    # 9. State reconciliation
    ("reconciliar-iguales", "reconciliación · igualdad", "Detectar estados equivalentes.", "a = {'x': 2}; b = {'x': 2}\nresultado = a == b\nprint(resultado)", True, "reconcile"),
    ("reconciliar-claves", "reconciliación · claves", "Detectar claves ausentes en cada réplica.", "a = {'x': 2, 'y': 1}; b = {'x': 2, 'z': 4}\nresultado = {'solo_a': sorted(a.keys() - b.keys()), 'solo_b': sorted(b.keys() - a.keys())}\nprint(resultado)", {"solo_a": ["y"], "solo_b": ["z"]}, "reconcile"),
    ("reconciliar-conflictos", "reconciliación · conflictos", "Listar valores distintos para claves comunes.", "a = {'x': 2, 'y': 1}; b = {'x': 3, 'y': 1}\nresultado = {k: (a[k], b[k]) for k in sorted(a.keys() & b.keys()) if a[k] != b[k]}\nprint(resultado)", {"x": (2, 3)}, "reconcile"),
    ("reconciliar-version", "reconciliación · versión", "Elegir el valor de mayor versión.", "a = {'version': 2, 'valor': 'viejo'}; b = {'version': 4, 'valor': 'nuevo'}\nresultado = max([a, b], key=lambda item: item['version'])\nprint(resultado)", {"version": 4, "valor": "nuevo"}, "reconcile"),
    ("reconciliar-plan", "reconciliación · plan", "Construir operaciones para igualar una réplica.", "origen = {'a': 2, 'b': 3}; destino = {'a': 1, 'c': 4}\nresultado = [('poner', k, origen[k]) for k in sorted(origen) if destino.get(k) != origen[k]] + [('borrar', k) for k in sorted(destino.keys() - origen.keys())]\nprint(resultado)", [("poner", "a", 2), ("poner", "b", 3), ("borrar", "c")], "reconcile"),
    ("reconciliar-suite", "reconciliación · suite", "Comparar versiones y producir estado convergente.", "replicas = [{'a': (2, 'x'), 'b': (1, 'm')}, {'a': (3, 'y'), 'c': (1, 'n')}]\nclaves = sorted(set().union(*(r.keys() for r in replicas)))\nresultado = {}\nfor clave in claves:\n    candidatos = [r[clave] for r in replicas if clave in r]; resultado[clave] = max(candidatos, key=lambda item: (item[0], item[1]))\nprint(resultado)", {"a": (3, "y"), "b": (1, "m"), "c": (1, "n")}, "reconcile"),

    # 10. Coordinated capstone
    ("coordinado-progreso", "capstone · progreso", "Combinar offsets por partición.", "eventos = [(0, 1), (1, 1), (0, 2)]\nresultado = {p: max(o for pp, o in eventos if pp == p) for p in sorted({p for p, _ in eventos})}\nprint(resultado)", {0: 2, 1: 1}, "capstone"),
    ("coordinado-confirmar", "capstone · confirmar", "Confirmar ids y obtener pendientes.", "enviados = ['e1', 'e2', 'e3']; acks = {'e1', 'e3'}\nresultado = [e for e in enviados if e not in acks]\nprint(resultado)", ["e2"], "capstone"),
    ("coordinado-snapshot", "capstone · snapshot", "Capturar progreso y agregado juntos.", "progreso = {0: 2, 1: 1}; total = {'a': 5}\nresultado = {'version': 1, 'progreso': dict(progreso), 'total': dict(total)}\nprint(resultado)", {"version": 1, "progreso": {0: 2, 1: 1}, "total": {"a": 5}}, "capstone"),
    ("coordinado-pausa", "capstone · pausa", "Aplicar backpressure mientras hay pendientes.", "creditos = 0; pendientes = ['e2']\nresultado = 'pausado' if pendientes and creditos == 0 else 'activo'\nprint(resultado)", "pausado", "capstone"),
    ("coordinado-replay", "capstone · replay", "Reproducir eventos nuevos de forma idempotente.", "vistos = {'e1'}; eventos = [('e1', 2), ('e2', 3)]\ntotal = 2\nfor identificador, valor in eventos:\n    if identificador not in vistos: vistos.add(identificador); total += valor\nresultado = (total, sorted(vistos))\nprint(resultado)", (5, ["e1", "e2"]), "capstone"),
    ("ola33-suite", "ola 33 · suite", "Cerrar la ola con offsets, acks, checkpoint, replay y reconciliación.", "snapshot = {'offset': 1, 'vistos': {'e1'}, 'total': {'a': 2}}\neventos = [(1, 'e1', 'a', 2), (2, 'e2', 'a', 3), (3, 'e3', 'b', 4), (3, 'e3', 'b', 4)]\nestado = {'offset': snapshot['offset'], 'vistos': set(snapshot['vistos']), 'total': dict(snapshot['total'])}\nfor offset, identificador, clave, valor in eventos:\n    if offset <= estado['offset'] or identificador in estado['vistos']: continue\n    estado['vistos'].add(identificador); estado['total'][clave] = estado['total'].get(clave, 0) + valor; estado['offset'] = offset\nresultado = {'offset': estado['offset'], 'vistos': sorted(estado['vistos']), 'total': dict(sorted(estado['total'].items())), 'checkpoint': 2}\nprint(resultado)", {"offset": 3, "vistos": ["e1", "e2", "e3"], "total": {"a": 5, "b": 4}, "checkpoint": 2}, "capstone"),
]

RAW = CASES


def build_raw(entries=CASES):
    assert len(entries) == 60
    return [exercise(2921 + index, *case) for index, case in enumerate(entries)]


if __name__ == "__main__":
    print(emit_rust(build_raw()))
